### ISSUE TITLE
No Module named jprops

### ISSUE THREAD

**Issue by friendlyfreedom** [kootstra/robotframework-allurereport#1]
First, thanks for all the work. Looks great. Tried to update from pypi package (1.1.1) to 1.2.0 version. When trying to install I'm getting: 

`D:\git\robotframework-allurereport>setup.py install
Traceback (most recent call last):
  File "D:\git\robotframework-allurereport\setup.py", line 2, in <module>
    from AllureReportLibrary.version import VERSION
  File "D:\git\robotframework-allurereport\AllureReportLibrary\__init__.py", line 1, in <module>
    from AllureReportLibrary import *
  File "D:\git\robotframework-allurereport\AllureReportLibrary\AllureReportLibrary.py", line 1, in <module>
    from AllureListener import AllureListener
  File "D:\git\robotframework-allurereport\AllureReportLibrary\AllureListener.py", line 25, in <module>
    import jprops
ImportError: No module named jprops`

Would be great if you could give some directions on this issue, or even better if i can upgrade from pypi

**Comment by kootstra** [comment]
There is a dependency on jprops. This can be installed using `pip install jprops`.

**Comment by friendlyfreedom** [comment]
Thanks. As you can tell I'm a novice pythoneer ;-) Full list of dependencies for others:
- jprops
- oauthlib
- sqlalchemy

Should be installed before setup.py of this package.
